
 A simple makefile consists of "rules" with the following shape:
 	
	target ... : prerequisites
		recipe
		...
		...

 A target is usually the name of a file that is generated by a program; examples of targets are executable or object files. A target can also be the name of an action to carry
 out, such as 'clean'.

 A prerequisite is a file that is used as input to create the target. A target often depends on several files.

 A recipe is an action that make carries out. A recipe may have more than one command, either on the same line or each on its own line. Tab character need to appear at the 
 beginning of every recipe line. .RECIPEPREFIX variable can be set to specify an alternate character.
