   - name: Installing apache2 and php
     hosts: abs
     remote_user: osergiyuk
     become_user: ansible
     become: yes
     vars:
       ansible_ssh_private_key_file: /home/osergiyuk/.ssh/id_rsa
       ansible_become_pass: child_In_Time3
       packages:
         - apache2
