---
- name: Test connection
  hosts: abs
  remote_user: osergiyuk
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/osergiyuk/.ssh/id_rsa

  tasks:
    - name: Test with ping module
      ping:
