
 A Dockerfile must start with a `FROM` instruction. It specifies a base image from which resulting image is belt. `FROM` may only be 
 preceded by by one or more `ARG` instructions, which declare arguments that are used in `FROM` lines in the Dockerfile.

 FROM <image>[:<tag>|@<digest>] [AS <name>]

  The FROM instruction initializes a new build stage and sets the Base image for the subsequent instructions. It can appear multiple times within a 
  single Dockerfile to create multiple images or use one build stage as a dependency for another. 


 WORKDIR   /path/to/workdir

  The WORKDIR instructions sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the 
  Dockerfile. If the WORKDIR doesn't exist, it will be created even if it's not used in any subsequent Dockerfile instruction.

  The WORKDIR instruction can be used multiple times in a Dockerfile. If a relative path is provided, it will be relative to the path
  of the previous WORKDIR instruction.

 ADD [--chown=<user>:<group>] <src>... <dest>
  
     Copies new files, directories or remote file URLs from <src> and adds them to the filesystem of the image at 
     the path <dest>.

 COPY [--chown=<user>:<group>] <src>... <dest>

     Copies new file or directories from <src> and adds them to the filesystem of the container at the path <dest>.

 RUN <command>
 RUN ["executable", "param1"[, "param12"]...]

     Execute any command in a new layer on top of the current image and commit the results. The resulting commited image will be
     used for the next step in the docker Dockerfile.
